// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AddIpAddressData, AddIpAddressErrors, AddIpAddressResponses, AddRestrictedPathData, AddRestrictedPathErrors, AddRestrictedPathResponses, DeleteIpAddressData, DeleteIpAddressErrors, DeleteIpAddressResponses, DeleteRestrictedPathData, DeleteRestrictedPathErrors, DeleteRestrictedPathResponses, GetIpAddressesData, GetIpAddressesErrors, GetIpAddressesResponses, GetMyIpAddressData, GetMyIpAddressErrors, GetMyIpAddressResponses, GetRestrictedPathsData, GetRestrictedPathsErrors, GetRestrictedPathsResponses, GetSettingsData, GetSettingsErrors, GetSettingsResponses, PingData, PingErrors, PingResponses, SaveSettingsData, SaveSettingsErrors, SaveSettingsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class M1SterPl0wUmbracoAccessRestrictionService {
    public static getIpAddresses<ThrowOnError extends boolean = false>(options?: Options<GetIpAddressesData, ThrowOnError>) {
        return (options?.client ?? client).get<GetIpAddressesResponses, GetIpAddressesErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/m1sterpl0wumbracoaccessrestriction/api/v1/ipaddresses',
            ...options
        });
    }
    
    public static addIpAddress<ThrowOnError extends boolean = false>(options?: Options<AddIpAddressData, ThrowOnError>) {
        return (options?.client ?? client).post<AddIpAddressResponses, AddIpAddressErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/m1sterpl0wumbracoaccessrestriction/api/v1/ipaddresses',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static deleteIpAddress<ThrowOnError extends boolean = false>(options: Options<DeleteIpAddressData, ThrowOnError>) {
        return (options.client ?? client).delete<DeleteIpAddressResponses, DeleteIpAddressErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/m1sterpl0wumbracoaccessrestriction/api/v1/ipaddresses/{ipAddress}',
            ...options
        });
    }
    
    public static getMyIpAddress<ThrowOnError extends boolean = false>(options?: Options<GetMyIpAddressData, ThrowOnError>) {
        return (options?.client ?? client).get<GetMyIpAddressResponses, GetMyIpAddressErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/m1sterpl0wumbracoaccessrestriction/api/v1/ipaddresses/mine',
            ...options
        });
    }
    
    public static getRestrictedPaths<ThrowOnError extends boolean = false>(options?: Options<GetRestrictedPathsData, ThrowOnError>) {
        return (options?.client ?? client).get<GetRestrictedPathsResponses, GetRestrictedPathsErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/m1sterpl0wumbracoaccessrestriction/api/v1/paths',
            ...options
        });
    }
    
    public static addRestrictedPath<ThrowOnError extends boolean = false>(options?: Options<AddRestrictedPathData, ThrowOnError>) {
        return (options?.client ?? client).post<AddRestrictedPathResponses, AddRestrictedPathErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/m1sterpl0wumbracoaccessrestriction/api/v1/paths',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static deleteRestrictedPath<ThrowOnError extends boolean = false>(options: Options<DeleteRestrictedPathData, ThrowOnError>) {
        return (options.client ?? client).delete<DeleteRestrictedPathResponses, DeleteRestrictedPathErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/m1sterpl0wumbracoaccessrestriction/api/v1/paths/{path}',
            ...options
        });
    }
    
    public static ping<ThrowOnError extends boolean = false>(options?: Options<PingData, ThrowOnError>) {
        return (options?.client ?? client).get<PingResponses, PingErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/m1sterpl0wumbracoaccessrestriction/api/v1/ping',
            ...options
        });
    }
    
    public static getSettings<ThrowOnError extends boolean = false>(options?: Options<GetSettingsData, ThrowOnError>) {
        return (options?.client ?? client).get<GetSettingsResponses, GetSettingsErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/m1sterpl0wumbracoaccessrestriction/api/v1/settings',
            ...options
        });
    }
    
    public static saveSettings<ThrowOnError extends boolean = false>(options?: Options<SaveSettingsData, ThrowOnError>) {
        return (options?.client ?? client).put<SaveSettingsResponses, SaveSettingsErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/m1sterpl0wumbracoaccessrestriction/api/v1/settings',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
}
