// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:5000' | (string & {});
};

export type AllowedIpAddressDto = {
    ipAddress: string;
    description?: string | null;
    createdDate?: string | null;
    createdBy?: string | null;
    canDelete: boolean;
};

export type CreateAllowedIpAddressRequest = {
    ipAddress: string;
    description?: string | null;
};

export type CreateRestrictedPathRequest = {
    path: string;
    description?: string | null;
};

export type RestrictedPathDto = {
    path: string;
    description?: string | null;
    createdDate?: string | null;
    createdBy?: string | null;
    canDelete: boolean;
};

export type SettingsDto = {
    enabled: boolean;
    isEnabledForced: boolean;
};

export type GetIpAddressesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/m1sterpl0wumbracoaccessrestriction/api/v1/ipaddresses';
};

export type GetIpAddressesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetIpAddressesResponses = {
    /**
     * OK
     */
    200: Array<AllowedIpAddressDto>;
};

export type GetIpAddressesResponse = GetIpAddressesResponses[keyof GetIpAddressesResponses];

export type AddIpAddressData = {
    body?: CreateAllowedIpAddressRequest;
    path?: never;
    query?: never;
    url: '/umbraco/m1sterpl0wumbracoaccessrestriction/api/v1/ipaddresses';
};

export type AddIpAddressErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Conflict
     */
    409: unknown;
};

export type AddIpAddressResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type DeleteIpAddressData = {
    body?: never;
    path: {
        ipAddress: string;
    };
    query?: never;
    url: '/umbraco/m1sterpl0wumbracoaccessrestriction/api/v1/ipaddresses/{ipAddress}';
};

export type DeleteIpAddressErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type DeleteIpAddressResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteIpAddressResponse = DeleteIpAddressResponses[keyof DeleteIpAddressResponses];

export type GetMyIpAddressData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/m1sterpl0wumbracoaccessrestriction/api/v1/ipaddresses/mine';
};

export type GetMyIpAddressErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetMyIpAddressResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetMyIpAddressResponse = GetMyIpAddressResponses[keyof GetMyIpAddressResponses];

export type GetRestrictedPathsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/m1sterpl0wumbracoaccessrestriction/api/v1/paths';
};

export type GetRestrictedPathsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetRestrictedPathsResponses = {
    /**
     * OK
     */
    200: Array<RestrictedPathDto>;
};

export type GetRestrictedPathsResponse = GetRestrictedPathsResponses[keyof GetRestrictedPathsResponses];

export type AddRestrictedPathData = {
    body?: CreateRestrictedPathRequest;
    path?: never;
    query?: never;
    url: '/umbraco/m1sterpl0wumbracoaccessrestriction/api/v1/paths';
};

export type AddRestrictedPathErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Conflict
     */
    409: unknown;
};

export type AddRestrictedPathResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type DeleteRestrictedPathData = {
    body?: never;
    path: {
        path: string;
    };
    query?: never;
    url: '/umbraco/m1sterpl0wumbracoaccessrestriction/api/v1/paths/{path}';
};

export type DeleteRestrictedPathErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type DeleteRestrictedPathResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteRestrictedPathResponse = DeleteRestrictedPathResponses[keyof DeleteRestrictedPathResponses];

export type PingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/m1sterpl0wumbracoaccessrestriction/api/v1/ping';
};

export type PingErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type PingResponses = {
    /**
     * OK
     */
    200: string;
};

export type PingResponse = PingResponses[keyof PingResponses];

export type GetSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/m1sterpl0wumbracoaccessrestriction/api/v1/settings';
};

export type GetSettingsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetSettingsResponses = {
    /**
     * OK
     */
    200: SettingsDto;
};

export type GetSettingsResponse = GetSettingsResponses[keyof GetSettingsResponses];

export type SaveSettingsData = {
    body?: SettingsDto;
    path?: never;
    query?: never;
    url: '/umbraco/m1sterpl0wumbracoaccessrestriction/api/v1/settings';
};

export type SaveSettingsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type SaveSettingsResponses = {
    /**
     * No Content
     */
    204: void;
};

export type SaveSettingsResponse = SaveSettingsResponses[keyof SaveSettingsResponses];
